name = "ValueAndGradient"
uuid = "b2a3a0f1-1884-4814-87af-a8eccdbd6af6"
version = "0.1.0"
authors = ["AstitvaAggarwal <astitvaaggarwalimportant@gmail.com>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"

[weakdeps]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
ValueAndGradientFiniteDifferencesExt = ["FiniteDifferences", "Test"]
ValueAndGradientMooncakeExt = "Mooncake"

[extras]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FiniteDifferences", "LinearAlgebra", "Mooncake", "Test"]

[compat]
ADTypes = "1"
FiniteDifferences = "0.12"
Mooncake = "0.4, 0.5, 0.6"
julia = "1.10"
